import React from 'react';

function Layer2(props) {

    return(
<div>
  <h1 style={{paddingTop: "0px"}}> Layer 1: They Must Be Heard </h1>

  <p>The first layer of our digital manuscript explains why and how the SLHP came into formation. It situates the University of North Carolina-Chapel Hill as the epicenter of debates about how to create sociological knowledge through efforts to identify and address the problems of the South during the 1920s and 1930s. It then recovers the political and cultural history that facilitated the creation of the SLHP as a project of the FWP under UNC Press Editor Couch.</p>
  <p>The layer is divided into sections. It begins with how the 1920s and 1930s cemented the University of North Carolina as a center of social science about the region at a time when the South was under a microscope for its economic precarity and social order. The desire to identify and address the problems of the South came as the institution of higher education aspired to become a national research university and thought leader on the region, which was signaled by two increasingly prestigious  institutional units: UNC Press and the Institute for Research in Social Sciences (IRSS). William “Bill” Couch, who took the reins of UNC Press in 1925 and became Director in 1932, published work that did not shy away from addressing the region’s problems in turn demonstrating that reflexive, critical scholarship could come from within the region.</p>
  <p>We then turn to how the stakes of the debate about how to represent the South heightened with the Great Depression, which placed the American South under a microscope. The region’s economic precarity combined with a culture of segregation further cemented the region’s reputation as anti-modern, backwards, and impervious to progress; questions about the region’s fitness for full inclusion and citizenship abounded. How to assess and represent the challenges of the region became a central concern. Two warring schools of intellectual thought framed the academic and literary representations of the South. The Agrarians, based at Vanderbilt University, romanticized a return to White rural, folk culture arguing sociological scholarship aided in the erosion of Southern traditional values. Howard Odum and his UNC-Chapel Hill colleagues, on the other hand, advocated for systematic, scientific studies of the region through fieldwork conducted by experts so that solutions to social problems could be identified. The evidence constructed a region that was distinct due to its regional culture but also a part of modernity and therefore the nation, earning them a reputation as advocates for “the New South”. These debates did not only play out in the academic and literary marketplace, but within the federal government as well.</p>
  <p>Next we reveal the critical role the federal government played in launching the SLHP. Part employment project and part laudatory experiment in federal support of cultural work, New Deal agencies such as the FWP pursued documentary projects and entered the fore over how to document and communicate the “real” conditions of people in the U.S.  Who should be documented, how they should be documented, and why they should be documented were key questions that animated the New Deal as well as Couch and Odum. While Couch and Odum worked closely together as UNC Press regularly pushed work by Odum’s IRSS Institute, Couch questioned if the academic prose driven by statistics that was becoming the norm for Sociology could communicate the challenges of the region to scholarly and popular audiences. He worried that such writing less accurately represented the actual lives of those being documented. With the support of the FWP’s Director Henry Alberg, Couch officially launched the life histories project upon being named the FWP’s Regional Director of the Southeastern region in 1938. With one foot in the federal government, which lent him the authority to pursue his new approach to documenting social conditions, and one foot in academia, as the director of the South’s most prominent press, Couch built the SLHP. </p>
  <p>We then turn to the aims of the SLHP. The method of “life histories” was an intentional intervention in debates about what counted as sociological knowledge during the era. Debates over how to capture and document social life abounded —whether through numbers and statistics in sociology, ethnographies from anthropology, first-hand stories through folklore, or through the increasingly broad category of “documentary.”  Couch conceptualized “life histories” as a more authentic form of documentation that amplified the voice of the interviewee. By recording these memories in the form of life histories, the project created a new method of collecting evidence about past and present social conditions by giving the people who were the subject of the sociological gaze of academics and the New Deal state a voice in the process rather than privileging sociological experts’ statistics or reducing their lives to romanticized folkways through folklore. Through narratives that emphasized qualitative rather than quantitative ways of knowing, readers could then more accurately and realistically access individuals’ experiences, which in turn served as a gateway to larger truths about Southern society. By tracking how the SLHP enacted this new method, we reveal how life histories made claims to authenticity, which on the one had worked against problematic stereotypes about work and labor in the region, while simultaneously reinscribed commonplace, problematic notions of race.</p>
  <p>We conclude the layer by investigating how Couch set-up the SLHP within the institutional structure of the FWP. Because writers were hired at the state level, he sent unemployed white-collar workers throughout their state to interview fellow Southerners about their lives and thereby shape Southern identities through their own words. As part of the Works Progress Administration (WPA), the life histories were collected by writers with varying levels of expertise, including creative writers, journalists, educators, and some who just marked ‘writing experience’ on their WPA applications. Writers, most of whom were White women, were sent out to different locations with an outline to follow when conducting interviews. However, they were given permission to diverge from the outline when necessary, because “the stories will not be usable if they are constructed on a rigid pattern,” Couch argued.  According to his instructions, their goal was “accuracy, human interest, social importance, and literary excellence,” which was to be achieved by telling the story “in the words of the persons who are consulted.”  At stake was method as well as power relations between intellectuals, academic disciplines, and the New Deal state. At the heart of this struggle were the actual people who were the subject of the documentary work to which the following layers will turn.</p>
  <p>Note about the digital layout for Layer 1: When the user selects Layer 1, they will see the text on the left-hand side and map on the right-hand side. This is the same as the Introduction (Figure 2). Because Layer 1 does address SLHP topics and themes, there will be hyperlinks in those sections to the topic model. When a user clicks on the link, the right side will toggle over to the “Topics” (Figure 6 and Figure 8). The radio button for “Map” and “Topics” always remain on the right side, so the user can toggle between the two as they see fit. </p>


</div>
    )
}


export {Layer2};
