import React from 'react';

function Layer3(props) {

    return(
<div>
  <h1 style={{paddingTop: "0px"}}> Layer 2: Placing the Life Histories </h1>

  <p>In Layer 2, we begin our turn to an analysis of the politics of representation of the SLHP through digital methods. While Layer 1 was dominated by a narrative built on archival material sharing the early history of the SLHP, the focus of Layer 2 is on using metadata from the archival material to spatially analyze the collection. With the help of an interactive map, we show the ways in which these life histories were ensconced in stories of place—a distinctly Southern space that Couch believed would help a national readership re-imagine Southern laborers as perceptive about their conditions, hard-working, and shaped by the past as well as the present rather than defined by stereotypes of the region as uneducated, lazy, and backwards. </p>
  <p>Reading the life histories through a spatial context allows users to see which geographic areas received the greatest representation. Interviews were conducted in states such as Alabama, South Carolina, and Virginia showing a concerted effort to document across the American South. The emphasis on Southeastern states also reveals the continued importance of and process of regional identity construction. Couch sought to use these place-based stories to challenge stereotypes of the region as socially and culturally regressive in order to position the South as a productive contributor to American society and therefore a benefit to the nation. Simultaneously, they reified regionalism by constructing the South geographically as the Southeastern states from Louisiana to Alabama and North Carolina to Florida showing national identity and regional particularities could be mutually reinforcing. </p>
  <p>At the same time, the cluster of interviews in North Carolina reveals the centrality the coastal state played in the documentary record. Interviews conducted in North Carolina constitute nearly 50% of the collection, which demonstrates the effect of Couch’s struggles to convince other states to participate. This is further evidenced by letters within the archival record. Moreover, the mapped data reveals that interviewers primarily visited small towns and rural areas, albeit only those surrounding metropolitan centers, which evidences Couch’s desire to raise the status of the rural South and the laborers within what he saw as exploitative systems such as mill work and tenant farming. Efforts to elevate the rural South came at a time of great anxiety that industrialization and migration were destroying local rural culture. The life histories sought to show how rural life was still foundational to Southern social life and identity rather than position these communities as economically and socially behind the times. While such an effort could have been the Agrarian’s dream, the life histories were not designed to romanticize agrarian labor but rather demonstrated the ways that the tenant farming system exploited laborers and served as a critique of industrial capitalism. </p>
  <p>We conclude by looking at how writers engaged with interviewees. Labeled by scholars as the “documentary decade,” the 1930s was a period in which cultural workers experimented with forms of documentary representation. As Farm Security Administration photographers such as Dorothea Lange pointed her camera at migrant farmers, life history writers such as Bernice Harris wrote the stories of tenant farmers. SLHP writers spent hours in people's homes chronicling their interviewee's lived experiences tasked with instructions from Couch that required them to write stories that would be “photographic in accuracy.” However, the instructions simultaneously demanded that writers should maintain authenticity by making sure the stories were simply told with interviewees speaking for themselves. These seemingly contradictory instructions that demanded the writers’ detached narrator description and at the same time the interviewee’s own voice were executed by writers with varying skill levels, proclivity for genres as well as personal prejudices. The result was uneven texts that give as much and likely more insight into the subjectivity of the writers than the subjectivity of the interviewees. We draw on scholars of the ethnographic and documentary encounter to explain how these interactions were an active, real-time negotiation that was shaped and reshaped by the positionality and subjectivity of the interviewer and interviewee. </p>
  <p>While seldom acknowledged, our data demonstrates that women were in fact central to the project. At a time when women were often relegated to the domestic sphere, the SLHP employed over ten women who set out across the South to record people’s stories. Their employment was not only a part of a shift in labor practices that would accelerate during World War II but aligned with the ideals, albeit rarely fully realized, of New Deal liberalism. The interviewers sought women’s stories guaranteeing representation in the documentary record and therefore inclusion into the national documentary record. Women discussed a range of themes such as domestic life and labor. Because of their gendered positionality, they also had unique access as women spoke with a level of candor reserved for those who they perceived as sharing a similar experience and sensibility. As a result, interviewees broached issues such as domestic abuse and prostitution offering a rare glimpse into taboo topics that shaped women’s daily lives, often as societal open secrets but culturally silenced. Moreover, this same positionality perceived as less threatening also resulted in women writers being sent to interviewee communities in marginalized positions including African Americans as well as immigrant classes that were not yet read as fully White. As a result, the vast majority of the life histories were written by women. While the SLHP offered some possibilities for new writers to enter the workforce, others were foreclosed. The SLHP hiring of exclusively White women, which reified segregationist economic practices, meant people of color and particularly women of color continued to be marginalized.</p>
  <p>Note about the digital layout for Layer 2: When the user selects Layer 2, they will see the text on the left-hand side and map on the right-hand side. This is the same as the Introduction (Figure 2) and Layer 1.  </p>

</div>
    )
}

export {Layer3};
